# Generated by Django 4.1.7 on 2023-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/img/ava.png', upload_to='../uploads/'),
        ),
    ]
