# Generated by Django 4.1.7 on 2023-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/img/ava.png', null=True, upload_to='uploads/', verbose_name='Avatar'),
        ),
    ]
