# Generated by Django 4.1.7 on 2023-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pubdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
