# Generated by Django 4.1.7 on 2023-04-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_alter_question_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pubdate',
            field=models.DateField(auto_now=True),
        ),
    ]
