# Generated by Django 4.1.7 on 2023-04-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_alter_question_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='askme.profile'),
        ),
    ]
